---
apiVersion: v1
kind: Namespace
metadata:
  name: claire-development
---
apiVersion: v1
kind: Namespace
metadata:
  name: josh-development
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: production